spring:
  profiles:
    #active: local
    active: prod
  application:
    name: knit-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    s3:
      bucket: haekyuawsbucket
    region:
      static: ap-northeast-2

kakao:
  #redirect-uri: http://localhost:8080/oauth2/callback/kakao
  redirect-uri:  http://3.38.127.168:8080/oauth2/callback/kakao/mobile/callback
  client-secret: 54XFhJwPlljHDyo91RXSDeJGwZN9CdND
  client-id: 22998f90bb6eacb75990ef920f6b3a04
  token-url: https://kauth.kakao.com/oauth/token

jwt:
  secret: wYJkPpJ0T8ZqvIQAyPfsl9B86zTZ/nUV3Pmy2GfQQve6c7vTc6YyR+o77urN2Cw8aVd4aQ==
  time: 2592000000 # (30일)