spring:
#  profiles:
#    active: oauth
  application:
    name: knit-api

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true

server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: haekyuawsbucket
    region:
      static: ap-northeast-2