spring:
  profiles:
    active: local,oauth,dev,prod
  application:
    name: knit-api

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true

server:
  port: 8080