name: CI/CD with systemd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - run: ./gradlew build -x test

      - name: Make SSH Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Copy JAR to EC2
        run: |
          echo "=== JAR 파일 전송 시작 ==="
          rsync -avzP -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            build/libs/knit-api-0.0.1-SNAPSHOT.jar \
            ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/knit-api/
          echo "=== JAR 파일 전송 완료 ==="

      - name: Deploy with systemd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 120s
          command_timeout: 3m
          script: |
            echo "=== 배포 시작 ==="
            
            cd /home/ubuntu/knit-api/
            
            echo "[1] 기존 서비스 중지"
            sudo systemctl stop knit-api || true
            
            echo "[2] 서비스 중지 대기"
            sleep 3
            
            echo "[3] 로그 파일 백업"
            if [ -f app.log ]; then
              mv app.log app.log.$(date +%Y%m%d_%H%M%S)
            fi
            
            echo "[4] JAR 파일 권한 설정"
            chmod 644 knit-api-0.0.1-SNAPSHOT.jar
            
            echo "[5] 새 서비스 시작"
            sudo systemctl start knit-api
            
            echo "[6] 서비스 시작 대기"
            sleep 10
            
            echo "[7] 서비스 상태 확인"
            sudo systemctl status knit-api --no-pager
            
            if sudo systemctl is-active --quiet knit-api; then
              echo "✅ 서비스가 정상적으로 실행 중입니다."
            else
              echo "❌ 서비스 시작에 실패했습니다."
              echo "=== 서비스 로그 ==="
              sudo journalctl -u knit-api --no-pager -n 30
              exit 1
            fi
            
            echo "=== 배포 완료 ==="